Recipe search
cse110-fa21-group30/cse110-fa21-group30 pull request #135
Opened 2021-12-04 23:11 UTC by Lexseal

### Features Added/Issues Addressed
* added dynamic refresh based on the filter on the search page
* allowed the enter key to function as the search button

### Brief Description of Solution
Created a global variable to store the fetched recipes and display a subset of the global recipes when the checkboxes are toggled.
Additionally, added the search function as an event listener for the enter key keyup event.

### Checklist
- [ ] Added new tests (You know the code best to make new tests)
- [x] Resolved merge conflicts (Prefer merge over rebase)
- [x] Status check passed (Linted and tested)
- [ ] Reviewed (At least one reviewer's approval)

### Caveat/Special Instructions for Team
None

2021-12-04 23:14 UTC, Lexseal commented on source/assets/scripts/backend.js
> +  if (tag['Vegan']) tag['Vegetarian'] = true;
saw a bunch of instances where a vegan thing isn't vegetarian so decided to fix it

2021-12-04 23:14 UTC, Lexseal commented on source/assets/scripts/recipe-searchPage.js
> +    if (e.key === 'Enter') hitSearch();  // enter key pressed
this fixes the enter key not searching

2021-12-04 23:14 UTC, Lexseal commented on source/assets/scripts/recipe-searchPage.js
> +function displayCards() {
factored this function outside so we can call when checkboxes are toggled

2021-12-04 23:14 UTC, Lexseal commented on source/assets/scripts/recipe-searchPage.js
> +let current_recipes = [];
this is all the recipes we have fetched from the backend

2021-12-05 01:52 UTC, yiw008 requested changes
/

2021-12-05 01:53 UTC, yiw008 commented on source/assets/scripts/recipe-detail.js
>    btn.addEventListener('click', () => window.history.back());
For a saved recipe, after I entered the recipe from dashboard, clicked the saved button (cancel favorite), and go back to dashboard, the recipe is still in the saved recipe list. That's why I need to check whether str is index.html.

2021-12-05 02:13 UTC, yiw008 approved these changes
Changed the goBack function in recipe-detail.js

2021-12-05 02:14 UTC, yiw008 commented
For a saved recipe, after I entered the recipe from dashboard, clicked the saved button (cancel favorite), and go back to dashboard, the recipe is still in the saved recipe list. To solve this problem, I need to check the str.

2021-12-05 02:38 UTC, merged